export async function getBetterAuthHeaders() {
  const headers = {
    "Content-Type": "application/json",
  };

  try {
    // Retrieve the JWT token generated by BetterAuth's server endpoint
    const res = await fetch("/api/auth/jwt", { cache: "no-store" });
    if (res.ok) {
      const data = await res.json().catch(() => ({}));
      const token = data?.token || data?.jwt;
      if (token) {
        headers["Authorization"] = `Bearer ${token}`;
      }
    }
  } catch {
    // If fetching token fails, return base Content-Type header
  }

  return headers;
}
